name: CI

on: [push, pull_request]

permissions:
  contents: read

jobs:
  build-and-lint:
    name: Build and lint

    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout git repository
        uses: actions/checkout@v7
      - name: Setup pnpm
        uses: pnpm/setup@v2
        with:
          cache: true
      - name: Lint
        run: pnpm lint
      - name: Detect unused code
        uses: fallow-rs/fallow@v3
      - name: Build frontend
        run: pnpm build:frontend
